### ISSUE TITLE
Request to Remove content from website

### ISSUE THREAD

**Issue by area63tony** [recoverysource/hugo-website#3]
AAWS/GSO is requesting that the PDFs of the Big Book and Daily Reflections be removed from the website.  Documentation below.

-------------------------

Greetings from the General Service Office of Alcoholics Anonymous.

 

Recently, we were advised by some of our fellowship that your site contained A.A. materials which are copyrighted by Alcoholics Anonymous World Services, Inc. (A.A.W.S.). While A.A.W.S.' copyrights are held in trust for A.A. as a whole, A.A.W.S. has a responsibility to protect these valuable A.A. assets (both in terms of contents ( i.e., preserving the integrity of the AA message), as well as otherwise). In order to meet this responsibility, A.A.W.S. must ensure that A.A.'s copyrights remain undiminished by infringing activities.

 

In reviewing your site, we noticed that you have included PDFs to full publications such as the fourth edition of Alcoholics Anonymous, the Big Book, and Daily Reflections under your “resources” tab. Guidelines for reprinting A.A. materials, describing what is, and what is not permissible by AA entities, are outlined in the [A.A. Service Manual](https://www.aa.org/sites/default/files/literature/en_bm-31_3.pdf). Generally, only overseas GSOs are permitted (by license) to translate and/or publish A.A. copyrighted materials in their entirety e.g., complete books, booklets, or pamphlets), though A.A. entities can certainly post short excerpts of A.A. literature.

 

In view of the foregoing, we ask that you remove these documents, and any material that does not follow the A.A. Service Manual. The fourth edition of The Big Book is complete on [aa.org](http://aa.org/), which you may link to along any other A.A. materials published there if you wish. If you have any questions about what may or may not be posted on your website, please let us know.

Warm regards,

 

Drew Deetz

Intellectual Property Administrator

General Service Office of Alcoholics Anonymous

475 Riverside Drive, 11th Floor

New York, NY 10115

(212) 870-3400 x 4725

[www.aa.org](http://www.aa.org/)

**Comment by MTecknology** [comment]
It's a shame that they claim integrity is their concern when this is one of the things they are definitively fighting against. Regardless, a take-down is a take-down and we'll get this taken down. :+1: Thanks for passing along the concern.

Note: The intention was to provide a stable/secure location for verified copies of freely-available content, which the meetings are entirely based around. This was an option for the people who got stuck outside of locked buildings and had meetings in parking lots. Most people without books found their way to the meeting through the website, and this had been a fast and convenient option to get material to newcomers. I'm disappointed that this is the response from the organaziton part of AA, but it's certainly theirs to control.

**Comment by area63tony** [comment]
Thanks Mike
